package com.opentae.data.mall.examples;

import java.util.ArrayList;
import java.util.List;
import com.opentae.common.beans.Example;


/**
 *
 *@author 自动生成
 *@see EsSynTemp
 *@docRoot com.opentae.data.mall.beans.EsSynTemp
 *@remark 自动生成
 *生成日期：2017-03-27 11:17:25
 *完成日期：
 *内容摘要：
 *
 */
public class EsSynTempExample extends Example{

	/**
     * This field was generated by ZHB Generator.
     * This field corresponds to the database table EsSynTemp
     *
     */
    protected String orderByClause;

    /**
     * This field was generated by ZHB Generator.
     * This field corresponds to the database table EsSynTemp
     *
     */
    protected boolean distinct;

    /**
     * This field was generated by ZHB Generator.
     * This field corresponds to the database table EsSynTemp
     *
     */
    protected List<Criteria> oredCriteria;

    /**
     * This field was generated by ZHB Generator.
     * This field corresponds to the database table EsSynTemp
     *
     */
    public EsSynTempExample(){
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This field was generated by ZHB Generator.
     * This field corresponds to the database table EsSynTemp
     *
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This field was generated by ZHB Generator.
     * This field corresponds to the database table EsSynTemp
     *
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This field was generated by ZHB Generator.
     * This field corresponds to the database table EsSynTemp
     *
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This field was generated by ZHB Generator.
     * This field corresponds to the database table EsSynTemp
     *
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This field was generated by ZHB Generator.
     * This field corresponds to the database table EsSynTemp
     *
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This field was generated by ZHB Generator.
     * This field corresponds to the database table EsSynTemp
     *
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This field was generated by ZHB Generator.
     * This field corresponds to the database table EsSynTemp
     *
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This field was generated by ZHB Generator.
     * This field corresponds to the database table EsSynTemp
     *
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This field was generated by ZHB Generator.
     * This field corresponds to the database table EsSynTemp
     *
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This field was generated by ZHB Generator.
     * This field corresponds to the database table EsSynTemp
     *
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }
    
     /**
     * This field was generated by ZHB Generator.
     * This field corresponds to the database table EsSynTemp
     *
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }
		public Criteria andCustomCondition(java.lang.String param,java.lang.String judge,java.lang.Object value){
            addCriterion(param + " " + judge + " ", value, param);
            return (Criteria) this;
        }
		public Criteria andCustomCondition(java.lang.String judge){
            addCriterion(judge);
            return (Criteria) this;
        }
        public Criteria andTempIdIsNull() {
            addCriterion("temp_id is null");
            return (Criteria) this;
        }

        public Criteria andTempIdIsNotNull() {
            addCriterion("temp_id is not null");
            return (Criteria) this;
        }

        public Criteria andTempIdEqualTo(java.lang.Long value) {
            addCriterion("temp_id =", value, "tempId");
            return (Criteria) this;
        }

        public Criteria andTempIdNotEqualTo(java.lang.Long value) {
            addCriterion("temp_id <>", value, "tempId");
            return (Criteria) this;
        }

        public Criteria andTempIdGreaterThan(java.lang.Long value) {
            addCriterion("temp_id >", value, "tempId");
            return (Criteria) this;
        }

        public Criteria andTempIdGreaterThanOrEqualTo(java.lang.Long value) {
            addCriterion("temp_id >=", value, "tempId");
            return (Criteria) this;
        }

        public Criteria andTempIdLessThan(java.lang.Long value) {
            addCriterion("temp_id <", value, "tempId");
            return (Criteria) this;
        }

        public Criteria andTempIdLessThanOrEqualTo(java.lang.Long value) {
            addCriterion("temp_id <=", value, "tempId");
            return (Criteria) this;
        }
		public Criteria andTempIdLike(java.lang.String value) {
            addCriterion("temp_id like", value, "tempId");
            return (Criteria) this;
        }

        public Criteria andTempIdNotLike(java.lang.String value) {
            addCriterion("temp_id not like", value, "tempId");
            return (Criteria) this;
        }
	        public Criteria andTempIdIn(List<java.lang.Long> values) {
            addCriterion("temp_id in", values, "tempId");
            return (Criteria) this;
        }

        public Criteria andTempIdNotIn(List<java.lang.Long> values) {
            addCriterion("temp_id not in", values, "tempId");
            return (Criteria) this;
        }

        public Criteria andTempIdBetween(java.lang.Long value1, java.lang.Long value2) {
            addCriterion("temp_id between", value1, value2, "tempId");
            return (Criteria) this;
        }

        public Criteria andTempIdNotBetween(java.lang.Long value1, java.lang.Long value2) {
            addCriterion("temp_id not between", value1, value2, "tempId");
            return (Criteria) this;
        }
        public Criteria andSynIdIsNull() {
            addCriterion("syn_id is null");
            return (Criteria) this;
        }

        public Criteria andSynIdIsNotNull() {
            addCriterion("syn_id is not null");
            return (Criteria) this;
        }

        public Criteria andSynIdEqualTo(java.lang.Long value) {
            addCriterion("syn_id =", value, "synId");
            return (Criteria) this;
        }

        public Criteria andSynIdNotEqualTo(java.lang.Long value) {
            addCriterion("syn_id <>", value, "synId");
            return (Criteria) this;
        }

        public Criteria andSynIdGreaterThan(java.lang.Long value) {
            addCriterion("syn_id >", value, "synId");
            return (Criteria) this;
        }

        public Criteria andSynIdGreaterThanOrEqualTo(java.lang.Long value) {
            addCriterion("syn_id >=", value, "synId");
            return (Criteria) this;
        }

        public Criteria andSynIdLessThan(java.lang.Long value) {
            addCriterion("syn_id <", value, "synId");
            return (Criteria) this;
        }

        public Criteria andSynIdLessThanOrEqualTo(java.lang.Long value) {
            addCriterion("syn_id <=", value, "synId");
            return (Criteria) this;
        }
		public Criteria andSynIdLike(java.lang.String value) {
            addCriterion("syn_id like", value, "synId");
            return (Criteria) this;
        }

        public Criteria andSynIdNotLike(java.lang.String value) {
            addCriterion("syn_id not like", value, "synId");
            return (Criteria) this;
        }
	        public Criteria andSynIdIn(List<java.lang.Long> values) {
            addCriterion("syn_id in", values, "synId");
            return (Criteria) this;
        }

        public Criteria andSynIdNotIn(List<java.lang.Long> values) {
            addCriterion("syn_id not in", values, "synId");
            return (Criteria) this;
        }

        public Criteria andSynIdBetween(java.lang.Long value1, java.lang.Long value2) {
            addCriterion("syn_id between", value1, value2, "synId");
            return (Criteria) this;
        }

        public Criteria andSynIdNotBetween(java.lang.Long value1, java.lang.Long value2) {
            addCriterion("syn_id not between", value1, value2, "synId");
            return (Criteria) this;
        }
        public Criteria andSynTypeIsNull() {
            addCriterion("syn_type is null");
            return (Criteria) this;
        }

        public Criteria andSynTypeIsNotNull() {
            addCriterion("syn_type is not null");
            return (Criteria) this;
        }

        public Criteria andSynTypeEqualTo(java.lang.Integer value) {
            addCriterion("syn_type =", value, "synType");
            return (Criteria) this;
        }

        public Criteria andSynTypeNotEqualTo(java.lang.Integer value) {
            addCriterion("syn_type <>", value, "synType");
            return (Criteria) this;
        }

        public Criteria andSynTypeGreaterThan(java.lang.Integer value) {
            addCriterion("syn_type >", value, "synType");
            return (Criteria) this;
        }

        public Criteria andSynTypeGreaterThanOrEqualTo(java.lang.Integer value) {
            addCriterion("syn_type >=", value, "synType");
            return (Criteria) this;
        }

        public Criteria andSynTypeLessThan(java.lang.Integer value) {
            addCriterion("syn_type <", value, "synType");
            return (Criteria) this;
        }

        public Criteria andSynTypeLessThanOrEqualTo(java.lang.Integer value) {
            addCriterion("syn_type <=", value, "synType");
            return (Criteria) this;
        }
		public Criteria andSynTypeLike(java.lang.String value) {
            addCriterion("syn_type like", value, "synType");
            return (Criteria) this;
        }

        public Criteria andSynTypeNotLike(java.lang.String value) {
            addCriterion("syn_type not like", value, "synType");
            return (Criteria) this;
        }
	        public Criteria andSynTypeIn(List<java.lang.Integer> values) {
            addCriterion("syn_type in", values, "synType");
            return (Criteria) this;
        }

        public Criteria andSynTypeNotIn(List<java.lang.Integer> values) {
            addCriterion("syn_type not in", values, "synType");
            return (Criteria) this;
        }

        public Criteria andSynTypeBetween(java.lang.Integer value1, java.lang.Integer value2) {
            addCriterion("syn_type between", value1, value2, "synType");
            return (Criteria) this;
        }

        public Criteria andSynTypeNotBetween(java.lang.Integer value1, java.lang.Integer value2) {
            addCriterion("syn_type not between", value1, value2, "synType");
            return (Criteria) this;
        }
        public Criteria andWebSiteIsNull() {
            addCriterion("web_site is null");
            return (Criteria) this;
        }

        public Criteria andWebSiteIsNotNull() {
            addCriterion("web_site is not null");
            return (Criteria) this;
        }

        public Criteria andWebSiteEqualTo(java.lang.String value) {
            addCriterion("web_site =", value, "webSite");
            return (Criteria) this;
        }

        public Criteria andWebSiteNotEqualTo(java.lang.String value) {
            addCriterion("web_site <>", value, "webSite");
            return (Criteria) this;
        }

        public Criteria andWebSiteGreaterThan(java.lang.String value) {
            addCriterion("web_site >", value, "webSite");
            return (Criteria) this;
        }

        public Criteria andWebSiteGreaterThanOrEqualTo(java.lang.String value) {
            addCriterion("web_site >=", value, "webSite");
            return (Criteria) this;
        }

        public Criteria andWebSiteLessThan(java.lang.String value) {
            addCriterion("web_site <", value, "webSite");
            return (Criteria) this;
        }

        public Criteria andWebSiteLessThanOrEqualTo(java.lang.String value) {
            addCriterion("web_site <=", value, "webSite");
            return (Criteria) this;
        }
		public Criteria andWebSiteLike(java.lang.String value) {
            addCriterion("web_site like", value, "webSite");
            return (Criteria) this;
        }

        public Criteria andWebSiteNotLike(java.lang.String value) {
            addCriterion("web_site not like", value, "webSite");
            return (Criteria) this;
        }
	        public Criteria andWebSiteIn(List<java.lang.String> values) {
            addCriterion("web_site in", values, "webSite");
            return (Criteria) this;
        }

        public Criteria andWebSiteNotIn(List<java.lang.String> values) {
            addCriterion("web_site not in", values, "webSite");
            return (Criteria) this;
        }

        public Criteria andWebSiteBetween(java.lang.String value1, java.lang.String value2) {
            addCriterion("web_site between", value1, value2, "webSite");
            return (Criteria) this;
        }

        public Criteria andWebSiteNotBetween(java.lang.String value1, java.lang.String value2) {
            addCriterion("web_site not between", value1, value2, "webSite");
            return (Criteria) this;
        }
    }

    /**
     * This field was generated by ZHB Generator.
     * This field corresponds to the database table EsSynTemp
     *
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This field was generated by ZHB Generator.
     * This field corresponds to the database table EsSynTemp
     *
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}
