@startuml

class GoatLocationVO{
-Long localId
-String code
-String description
}

abstract class GoatLocation{
+List<Goat> selGoats()
}

interface Goat{

void publish()
void preparePublish(Long second)
}

class GoatVO{
-Long localId
-Long goatId
}

class ImgGoatVO{
-String picUrl
-String linkUrl
}

class ItemUpVO{
-Long realNum //真实上款量
-Long unRealNum //不真实的上款量
}

class ItemGoatVO{
-Long itemId
-String title
-String picUrl
}

abstract class ImgGoat{

}

abstract class ItemGoat{

}

interface ItemResort{
ItemUpVO selUp() //查询真实上款量与虚假上款量
void modifyUp(Integer num) //修改虚假上款量
Double selWeight() //查询权重
void updateWeight(Double num)  //修改权重
}

GoatLocationVO <|-- GoatLocation

GoatLocation *-- Goat

Goat <|.. ImgGoat

Goat <|.. ItemGoat

GoatVO <|-- ImgGoatVO
GoatVO <|-- ItemGoatVO

ImgGoatVO <|-- ImgGoat

ItemGoatVO <|-- ItemGoat

ItemResort <|.. ItemGoat

ItemUpVO o-- ItemResort

interface GoatFactory{
GoatLocation getALocation(String code)
GoatLocation getALocationByVo(GoatLocationVO vo)
Goat selGoatById(Long goatId)
Goat selGoatByVo(GoatVO goatVO)
}

note left of GoatFactory:广告服务

@enduml