@startuml
enum PayType{
XZ  //星座
ALI  //阿里
WX   //微信
}
interface Cart{
void addProduct(Product pro);
void rmProduct(Product pro);
Long modifyProductNumber(Long pid,Integer number);
}
interface Order{
PayApplyVO payApply(PayType type);//支付申请
Long pay(Long applyId,Long money);//付款确认

void refunds(Long money);//全单退订

}

interface ItemOrder{
LogisticsVO selLogistics();//查询物流单号
void sended(LogisticsVO logistics);//发货完成

PayApplyVO repayAppy(PayType type,List<SubOrderVO> orders);
void refundLogistics(Long money);//退邮费
void refundGift(Long money);//退礼品费
void refundPackage(Long money);//退包材
void refundService(Long money);//退服务
}

interface RechangeOrder{

}

interface SubOrder{
void refund(Long money);//退货
}

interface SubItemOrder{

}
interface Product{
List<SkuVO> selSkus();
}

interface ItemProduct{
void modifyWeight(Long meter);
void modifyPrice(Long price);
}

interface Sender{
void sendOrder(Order order);//发放订单给代发
}

class OrderVO{
-Long orderId;
-OrderType type;
-Long totalFee;
-List<Long> payIds;
-Long refundFee;//已退金额
}

class ItemOrderVO{
-OrderStatus status;
-List<packageVO> packages;//包材
-List<LogisticsVO> logistics;//物流
-SenderVO sender;//发件单位
-List<ServiceVO> services;//服务信息
}

class SubOrderVO{
-Long subOrderId;
-Long orderId;
-Long refundFee;//已退金额
}

class SubItemOrderVO{
-ProductVO product;
-Integer number;
-OrderStatus status;
}

enum ProductType{
XZ_ITEM //星座商品

}

enum OrderType{
XZ //星座商品的订单

}

enum OrderStatus{
WAIT_BUYER_PAY //等待买家付款
SELLER_CONSIGNED_PART //卖家部分发货
WAIT_SELLER_SEND_GOODS //等待卖家发货
TRADE_FINISHED  //交易完成
TRADE_CLOSED  //付款以后用户退款成功，交易自动关闭

}

class ItemProductVO{
-Long pid;
-Long goodsId;
-String webSite;
-String picUrl;
-String title;
-Long price;
-String marketName;
-String floor;
-String shopNum;
-Long marketId;
-Long floorId;
-Long shopId;
-Long weight;
-ItemSkuVO sku;
}

class ItemSkuVO{
-Long skuId;
-Long pid;
-String color;
-String size;
}

class PayApplyVO{
-Long applyId;//支付申请ID
-Long money;
-String payLink;//支付链接
-PayType payType;//支付类型
-Date createTime;//创建时间
-Integer payFor;//付款理由
}

class SenderVO{
-Long senderId;//发件单位ID
-String webSite;//分站
-String topic;//主题
}

class LogisticsVO{
-Long id;
-Long companyId;//快递公司ID
-Long addressId;//地址
-String courierNumber;//快递单号
-Long oid;//订单ID
-Long money;//支付金额,钱为单位
}

class MetarialVO{
-Long id;
-String name;
-Integer size;//尺寸
-Long price;//价格
}

class ServiceVO{
-Long id;//主键
-Long price;//费用
-String text;//服务描述
-Integer flag;//服务标识
}

Cart *-- Product
Product <|-- ItemProduct
ItemProduct <|-- ItemProductVO
ItemProductVO --o ItemSkuVO

SubOrder <|-- SubItemOrder
Order <|-- ItemOrder
Order <|-- RechangeOrder
ItemOrder *-- SubItemOrder

OrderVO <|-- ItemOrderVO
SubOrderVO <|-- SubItemOrderVO

ItemOrderVO *-- SubItemOrderVO
ItemOrderVO --o ServiceVO

ItemOrderVO --o SenderVO
ItemOrderVO --o MetarialVO
ItemOrderVO --o LogisticsVO

Order --o PayApplyVO

SenderVO --> Sender


@enduml