@startuml
enum PayType{
XZ  //星座
ALI  //阿里
WX   //微信
}

interface Order{
PayApplyVO payApply(PayType type);//支付申请
Long pay(Long applyId,Long money);//付款确认

void refunds(Long money);//全单退订

}

interface ItemOrder{
LogisticsVO selLogistics();//查询物流单号
void sended(LogisticsVO logistics);//发货完成

PayApplyVO repayAppy(PayType type,List<SubOrderVO> orders);
void refundLogistics(Long money);//退邮费
void refundGift(Long money);//退礼品费
void refundPackage(Long money);//退包材
void refundService(Long money);//退服务
}

interface RechangeOrder{

}

interface SubOrder{
void refund(Long money);//退货
}

interface SubItemOrder{

}

interface Sender{
void sendOrder(Order order);//发放订单给代发
}

enum ProductType{
XZ_ITEM //星座商品

}

enum OrderType{
XZ //星座商品的订单

}

enum OrderStatus{
WAIT_BUYER_PAY //等待买家付款
SELLER_CONSIGNED_PART //卖家部分发货
WAIT_SELLER_SEND_GOODS //等待卖家发货
TRADE_FINISHED  //交易完成
TRADE_CLOSED  //付款以后用户退款成功，交易自动关闭

}



class PayApplyVO{
-Long applyId;//支付申请ID
-Long money;
-String payLink;//支付链接
-PayType payType;//支付类型
-Date createTime;//创建时间
-Integer payFor;//付款理由
}

SubOrder <|-- SubItemOrder
Order <|-- ItemOrder
Order <|-- RechangeOrder
ItemOrder *-- SubItemOrder
Sender *-- Order

Order --o PayApplyVO


@enduml