package com.opentae.data.daifa.examples;

import java.util.ArrayList;
import java.util.List;

import com.opentae.common.beans.Example;
/**
 *==========================================================
 *TODO
 *@类编号：
 *@类名称：DaifaCallExpressExample.java
 *@文件路径：com.opentae.data.daifa.examples.DaifaCallExpressExample
 *@内容摘要：
 *@编码作者：自动生成
 *@完成日期：
 *@Date2017-08-09 05:46:03
 *@comments:
 *
 *=========================================================
 */
public class DaifaCallExpressExample extends Example{

	/**
     * This field was generated by ZHB Generator.
     * This field corresponds to the database table DaifaCallExpress
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by ZHB Generator.
     * This field corresponds to the database table DaifaCallExpress
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by ZHB Generator.
     * This field corresponds to the database table DaifaCallExpress
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This field was generated by ZHB Generator.
     * This field corresponds to the database table DaifaCallExpress
     *
     * @mbggenerated
     */
    public DaifaCallExpressExample(){
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This field was generated by ZHB Generator.
     * This field corresponds to the database table DaifaCallExpress
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This field was generated by ZHB Generator.
     * This field corresponds to the database table DaifaCallExpress
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This field was generated by ZHB Generator.
     * This field corresponds to the database table DaifaCallExpress
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This field was generated by ZHB Generator.
     * This field corresponds to the database table DaifaCallExpress
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This field was generated by ZHB Generator.
     * This field corresponds to the database table DaifaCallExpress
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This field was generated by ZHB Generator.
     * This field corresponds to the database table DaifaCallExpress
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This field was generated by ZHB Generator.
     * This field corresponds to the database table DaifaCallExpress
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This field was generated by ZHB Generator.
     * This field corresponds to the database table DaifaCallExpress
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This field was generated by ZHB Generator.
     * This field corresponds to the database table DaifaCallExpress
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This field was generated by ZHB Generator.
     * This field corresponds to the database table DaifaCallExpress
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }
    
     /**
     * This field was generated by ZHB Generator.
     * This field corresponds to the database table DaifaCallExpress
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }
        public Criteria andDfTradeIdIsNull() {
            addCriterion("df_trade_id is null");
            return (Criteria) this;
        }

        public Criteria andDfTradeIdIsNotNull() {
            addCriterion("df_trade_id is not null");
            return (Criteria) this;
        }

        public Criteria andDfTradeIdEqualTo(Long value) {
            addCriterion("df_trade_id =", value, "dfTradeId");
            return (Criteria) this;
        }

        public Criteria andDfTradeIdNotEqualTo(Long value) {
            addCriterion("df_trade_id <>", value, "dfTradeId");
            return (Criteria) this;
        }

        public Criteria andDfTradeIdGreaterThan(Long value) {
            addCriterion("df_trade_id >", value, "dfTradeId");
            return (Criteria) this;
        }

        public Criteria andDfTradeIdGreaterThanOrEqualTo(Long value) {
            addCriterion("df_trade_id >=", value, "dfTradeId");
            return (Criteria) this;
        }

        public Criteria andDfTradeIdLessThan(Long value) {
            addCriterion("df_trade_id <", value, "dfTradeId");
            return (Criteria) this;
        }

        public Criteria andDfTradeIdLessThanOrEqualTo(Long value) {
            addCriterion("df_trade_id <=", value, "dfTradeId");
            return (Criteria) this;
        }
        
				public Criteria andDfTradeIdLike(String value) {
            addCriterion("df_trade_id like", value, "dfTradeId");
            return (Criteria) this;
        }
		
        public Criteria andDfTradeIdNotLike(String value) {
            addCriterion("df_trade_id not like", value, "dfTradeId");
            return (Criteria) this;
        }
        
        public Criteria andDfTradeIdIn(List<Long> values) {
            addCriterion("df_trade_id in", values, "dfTradeId");
            return (Criteria) this;
        }

		
        public Criteria andDfTradeIdNotIn(List<Long> values) {
            addCriterion("df_trade_id not in", values, "dfTradeId");
            return (Criteria) this;
        }

        public Criteria andDfTradeIdBetween(Long value1, Long value2) {
            addCriterion("df_trade_id between", value1, value2, "dfTradeId");
            return (Criteria) this;
        }

        public Criteria andDfTradeIdNotBetween(Long value1, Long value2) {
            addCriterion("df_trade_id not between", value1, value2, "dfTradeId");
            return (Criteria) this;
        }
        public Criteria andSellerIdIsNull() {
            addCriterion("seller_id is null");
            return (Criteria) this;
        }

        public Criteria andSellerIdIsNotNull() {
            addCriterion("seller_id is not null");
            return (Criteria) this;
        }

        public Criteria andSellerIdEqualTo(Long value) {
            addCriterion("seller_id =", value, "sellerId");
            return (Criteria) this;
        }

        public Criteria andSellerIdNotEqualTo(Long value) {
            addCriterion("seller_id <>", value, "sellerId");
            return (Criteria) this;
        }

        public Criteria andSellerIdGreaterThan(Long value) {
            addCriterion("seller_id >", value, "sellerId");
            return (Criteria) this;
        }

        public Criteria andSellerIdGreaterThanOrEqualTo(Long value) {
            addCriterion("seller_id >=", value, "sellerId");
            return (Criteria) this;
        }

        public Criteria andSellerIdLessThan(Long value) {
            addCriterion("seller_id <", value, "sellerId");
            return (Criteria) this;
        }

        public Criteria andSellerIdLessThanOrEqualTo(Long value) {
            addCriterion("seller_id <=", value, "sellerId");
            return (Criteria) this;
        }
        
				public Criteria andSellerIdLike(String value) {
            addCriterion("seller_id like", value, "sellerId");
            return (Criteria) this;
        }
		
        public Criteria andSellerIdNotLike(String value) {
            addCriterion("seller_id not like", value, "sellerId");
            return (Criteria) this;
        }
        
        public Criteria andSellerIdIn(List<Long> values) {
            addCriterion("seller_id in", values, "sellerId");
            return (Criteria) this;
        }

		
        public Criteria andSellerIdNotIn(List<Long> values) {
            addCriterion("seller_id not in", values, "sellerId");
            return (Criteria) this;
        }

        public Criteria andSellerIdBetween(Long value1, Long value2) {
            addCriterion("seller_id between", value1, value2, "sellerId");
            return (Criteria) this;
        }

        public Criteria andSellerIdNotBetween(Long value1, Long value2) {
            addCriterion("seller_id not between", value1, value2, "sellerId");
            return (Criteria) this;
        }
        public Criteria andExpressIdIsNull() {
            addCriterion("express_id is null");
            return (Criteria) this;
        }

        public Criteria andExpressIdIsNotNull() {
            addCriterion("express_id is not null");
            return (Criteria) this;
        }

        public Criteria andExpressIdEqualTo(Long value) {
            addCriterion("express_id =", value, "expressId");
            return (Criteria) this;
        }

        public Criteria andExpressIdNotEqualTo(Long value) {
            addCriterion("express_id <>", value, "expressId");
            return (Criteria) this;
        }

        public Criteria andExpressIdGreaterThan(Long value) {
            addCriterion("express_id >", value, "expressId");
            return (Criteria) this;
        }

        public Criteria andExpressIdGreaterThanOrEqualTo(Long value) {
            addCriterion("express_id >=", value, "expressId");
            return (Criteria) this;
        }

        public Criteria andExpressIdLessThan(Long value) {
            addCriterion("express_id <", value, "expressId");
            return (Criteria) this;
        }

        public Criteria andExpressIdLessThanOrEqualTo(Long value) {
            addCriterion("express_id <=", value, "expressId");
            return (Criteria) this;
        }
        
				public Criteria andExpressIdLike(String value) {
            addCriterion("express_id like", value, "expressId");
            return (Criteria) this;
        }
		
        public Criteria andExpressIdNotLike(String value) {
            addCriterion("express_id not like", value, "expressId");
            return (Criteria) this;
        }
        
        public Criteria andExpressIdIn(List<Long> values) {
            addCriterion("express_id in", values, "expressId");
            return (Criteria) this;
        }

		
        public Criteria andExpressIdNotIn(List<Long> values) {
            addCriterion("express_id not in", values, "expressId");
            return (Criteria) this;
        }

        public Criteria andExpressIdBetween(Long value1, Long value2) {
            addCriterion("express_id between", value1, value2, "expressId");
            return (Criteria) this;
        }

        public Criteria andExpressIdNotBetween(Long value1, Long value2) {
            addCriterion("express_id not between", value1, value2, "expressId");
            return (Criteria) this;
        }
        public Criteria andExpressCodeIsNull() {
            addCriterion("express_code is null");
            return (Criteria) this;
        }

        public Criteria andExpressCodeIsNotNull() {
            addCriterion("express_code is not null");
            return (Criteria) this;
        }

        public Criteria andExpressCodeEqualTo(String value) {
            addCriterion("express_code =", value, "expressCode");
            return (Criteria) this;
        }

        public Criteria andExpressCodeNotEqualTo(String value) {
            addCriterion("express_code <>", value, "expressCode");
            return (Criteria) this;
        }

        public Criteria andExpressCodeGreaterThan(String value) {
            addCriterion("express_code >", value, "expressCode");
            return (Criteria) this;
        }

        public Criteria andExpressCodeGreaterThanOrEqualTo(String value) {
            addCriterion("express_code >=", value, "expressCode");
            return (Criteria) this;
        }

        public Criteria andExpressCodeLessThan(String value) {
            addCriterion("express_code <", value, "expressCode");
            return (Criteria) this;
        }

        public Criteria andExpressCodeLessThanOrEqualTo(String value) {
            addCriterion("express_code <=", value, "expressCode");
            return (Criteria) this;
        }
        
				public Criteria andExpressCodeLike(String value) {
            addCriterion("express_code like", value, "expressCode");
            return (Criteria) this;
        }
		
        public Criteria andExpressCodeNotLike(String value) {
            addCriterion("express_code not like", value, "expressCode");
            return (Criteria) this;
        }
        
        public Criteria andExpressCodeIn(List<String> values) {
            addCriterion("express_code in", values, "expressCode");
            return (Criteria) this;
        }

		
        public Criteria andExpressCodeNotIn(List<String> values) {
            addCriterion("express_code not in", values, "expressCode");
            return (Criteria) this;
        }

        public Criteria andExpressCodeBetween(String value1, String value2) {
            addCriterion("express_code between", value1, value2, "expressCode");
            return (Criteria) this;
        }

        public Criteria andExpressCodeNotBetween(String value1, String value2) {
            addCriterion("express_code not between", value1, value2, "expressCode");
            return (Criteria) this;
        }
        public Criteria andMarkDestinationIsNull() {
            addCriterion("mark_destination is null");
            return (Criteria) this;
        }

        public Criteria andMarkDestinationIsNotNull() {
            addCriterion("mark_destination is not null");
            return (Criteria) this;
        }

        public Criteria andMarkDestinationEqualTo(String value) {
            addCriterion("mark_destination =", value, "markDestination");
            return (Criteria) this;
        }

        public Criteria andMarkDestinationNotEqualTo(String value) {
            addCriterion("mark_destination <>", value, "markDestination");
            return (Criteria) this;
        }

        public Criteria andMarkDestinationGreaterThan(String value) {
            addCriterion("mark_destination >", value, "markDestination");
            return (Criteria) this;
        }

        public Criteria andMarkDestinationGreaterThanOrEqualTo(String value) {
            addCriterion("mark_destination >=", value, "markDestination");
            return (Criteria) this;
        }

        public Criteria andMarkDestinationLessThan(String value) {
            addCriterion("mark_destination <", value, "markDestination");
            return (Criteria) this;
        }

        public Criteria andMarkDestinationLessThanOrEqualTo(String value) {
            addCriterion("mark_destination <=", value, "markDestination");
            return (Criteria) this;
        }
        
				public Criteria andMarkDestinationLike(String value) {
            addCriterion("mark_destination like", value, "markDestination");
            return (Criteria) this;
        }
		
        public Criteria andMarkDestinationNotLike(String value) {
            addCriterion("mark_destination not like", value, "markDestination");
            return (Criteria) this;
        }
        
        public Criteria andMarkDestinationIn(List<String> values) {
            addCriterion("mark_destination in", values, "markDestination");
            return (Criteria) this;
        }

		
        public Criteria andMarkDestinationNotIn(List<String> values) {
            addCriterion("mark_destination not in", values, "markDestination");
            return (Criteria) this;
        }

        public Criteria andMarkDestinationBetween(String value1, String value2) {
            addCriterion("mark_destination between", value1, value2, "markDestination");
            return (Criteria) this;
        }

        public Criteria andMarkDestinationNotBetween(String value1, String value2) {
            addCriterion("mark_destination not between", value1, value2, "markDestination");
            return (Criteria) this;
        }
        public Criteria andPackageNameIsNull() {
            addCriterion("package_name is null");
            return (Criteria) this;
        }

        public Criteria andPackageNameIsNotNull() {
            addCriterion("package_name is not null");
            return (Criteria) this;
        }

        public Criteria andPackageNameEqualTo(String value) {
            addCriterion("package_name =", value, "packageName");
            return (Criteria) this;
        }

        public Criteria andPackageNameNotEqualTo(String value) {
            addCriterion("package_name <>", value, "packageName");
            return (Criteria) this;
        }

        public Criteria andPackageNameGreaterThan(String value) {
            addCriterion("package_name >", value, "packageName");
            return (Criteria) this;
        }

        public Criteria andPackageNameGreaterThanOrEqualTo(String value) {
            addCriterion("package_name >=", value, "packageName");
            return (Criteria) this;
        }

        public Criteria andPackageNameLessThan(String value) {
            addCriterion("package_name <", value, "packageName");
            return (Criteria) this;
        }

        public Criteria andPackageNameLessThanOrEqualTo(String value) {
            addCriterion("package_name <=", value, "packageName");
            return (Criteria) this;
        }
        
				public Criteria andPackageNameLike(String value) {
            addCriterion("package_name like", value, "packageName");
            return (Criteria) this;
        }
		
        public Criteria andPackageNameNotLike(String value) {
            addCriterion("package_name not like", value, "packageName");
            return (Criteria) this;
        }
        
        public Criteria andPackageNameIn(List<String> values) {
            addCriterion("package_name in", values, "packageName");
            return (Criteria) this;
        }

		
        public Criteria andPackageNameNotIn(List<String> values) {
            addCriterion("package_name not in", values, "packageName");
            return (Criteria) this;
        }

        public Criteria andPackageNameBetween(String value1, String value2) {
            addCriterion("package_name between", value1, value2, "packageName");
            return (Criteria) this;
        }

        public Criteria andPackageNameNotBetween(String value1, String value2) {
            addCriterion("package_name not between", value1, value2, "packageName");
            return (Criteria) this;
        }
        public Criteria andJsonDataIsNull() {
            addCriterion("json_data is null");
            return (Criteria) this;
        }

        public Criteria andJsonDataIsNotNull() {
            addCriterion("json_data is not null");
            return (Criteria) this;
        }

        public Criteria andJsonDataEqualTo(String value) {
            addCriterion("json_data =", value, "jsonData");
            return (Criteria) this;
        }

        public Criteria andJsonDataNotEqualTo(String value) {
            addCriterion("json_data <>", value, "jsonData");
            return (Criteria) this;
        }

        public Criteria andJsonDataGreaterThan(String value) {
            addCriterion("json_data >", value, "jsonData");
            return (Criteria) this;
        }

        public Criteria andJsonDataGreaterThanOrEqualTo(String value) {
            addCriterion("json_data >=", value, "jsonData");
            return (Criteria) this;
        }

        public Criteria andJsonDataLessThan(String value) {
            addCriterion("json_data <", value, "jsonData");
            return (Criteria) this;
        }

        public Criteria andJsonDataLessThanOrEqualTo(String value) {
            addCriterion("json_data <=", value, "jsonData");
            return (Criteria) this;
        }
        
				public Criteria andJsonDataLike(String value) {
            addCriterion("json_data like", value, "jsonData");
            return (Criteria) this;
        }
		
        public Criteria andJsonDataNotLike(String value) {
            addCriterion("json_data not like", value, "jsonData");
            return (Criteria) this;
        }
        
        public Criteria andJsonDataIn(List<String> values) {
            addCriterion("json_data in", values, "jsonData");
            return (Criteria) this;
        }

		
        public Criteria andJsonDataNotIn(List<String> values) {
            addCriterion("json_data not in", values, "jsonData");
            return (Criteria) this;
        }

        public Criteria andJsonDataBetween(String value1, String value2) {
            addCriterion("json_data between", value1, value2, "jsonData");
            return (Criteria) this;
        }

        public Criteria andJsonDataNotBetween(String value1, String value2) {
            addCriterion("json_data not between", value1, value2, "jsonData");
            return (Criteria) this;
        }
        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(java.util.Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(java.util.Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(java.util.Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(java.util.Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(java.util.Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(java.util.Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }
        
				public Criteria andCreateTimeLike(String value) {
            addCriterion("create_time like", value, "createTime");
            return (Criteria) this;
        }
		
        public Criteria andCreateTimeNotLike(String value) {
            addCriterion("create_time not like", value, "createTime");
            return (Criteria) this;
        }
        
        public Criteria andCreateTimeIn(List<java.util.Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

		
        public Criteria andCreateTimeNotIn(List<java.util.Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(java.util.Date value1, java.util.Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(java.util.Date value1, java.util.Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }
    }

    /**
     * This field was generated by ZHB Generator.
     * This field corresponds to the database table DaifaCallExpress
     *
     * @mbggenerated
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This field was generated by ZHB Generator.
     * This field corresponds to the database table DaifaCallExpress
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}
